# Ref. http://about.travis-ci.org/docs/user/languages/python/
language: python
python:
    - 2.4
    - 2.5
    - 2.6
    - 2.7
    #- 3.2
#matrix:
#    include:
#        - python: 2.4
#          env: FULL="true"
#        - python: 2.5
#          env: FULL="true"
#        - python: 2.6
#          env: FULL="true"
#        - python: 2.7
#          env: FULL="true"
##        - python: 3.2
##          env: LANG="en_US.utf-8"
install:
    - if [[ $TRAVIS_PYTHON_VERSION < '2.6' ]]; then pip install --use-mirrors python-simplejson PyYAML; fi
    - if [[ $TRAVIS_PYTHON_VERSION >= '2.6' ]]; then pip install --use-mirrors PyYAML; fi
script:
    - aux/runtest.sh
